### ISSUE TITLE
Quickbar Templates ideas

### ISSUE THREAD

**Issue by DonGufo** [raiguard/Factorio-SmallMods#21]
I was very happy when i found out that this mod used combinators to encode the quicbars, I tryed pasting the blueprint for easyer visualization and reorganization, and I realized that it requiered special tags and factorio doens't allow to copy and paste them. 

One option that comes to mind would be a tool that creates the tags when it finds a 10x10 of constant combinators.

Another feature that i think would be usefull by itself and could addres the previous issue in a different way, is the possibility to import a template that only adds items that are present and does nothing with the empy slots in the blueprint, for example with a second GUI button so that it's possible to have small sections of templates without having to make one for every possible combination

**Comment by raiguard** [comment]
The tags thing was purely due to my pride, and I have released a patch to fix it. I wanted "clean code" and didn't want to mess with position-based indexing anymore. But, I realized the error of my ways, and now templates that you get / place in the actual world will work again. I apologize!

As for your feature request, I've gone ahead and added it:
![image](https://user-images.githubusercontent.com/3515394/93416254-a069e780-f862-11ea-88f3-c061f7392ae2.png)
