### ISSUE TITLE
crash with mouse click into empty search field

### ISSUE THREAD

**Issue by bgn68** [raiguard/Factorio-SmallMods#7]
Die Mod Quick Item Search (1.4.0) hat einen Fehler verursacht, der nicht behoben werden kann. 
Bitte informiere den Autor der Mod über diesen Fehler. 
 
Error while running event QuickItemSearch::on_gui_click (ID 1) 
Expected sprite button or sprite. 
stack traceback: 
        __QuickItemSearch__/control.lua:350: in function 'handler' 
        __RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28> 
stack traceback: 
        [C]: in function '__index' 
        __QuickItemSearch__/control.lua:350: in function 'handler' 
        __RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:29>
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
-- VISUELL --                                       12        1,1         Alles

**Comment by raiguard** [comment]
Thanks for the report. This is fixed as a side effect of the complete rewrite of the mod that I have done over the last few days, so it will be fixed in the next version!

As a side note, QIS no longer lives in this repository. I have graduated it to its [own repository](https://github.com/raiguard/Factorio-QuickItemSearch), as the size and scope of the mod has outgrown the "small mod" moniker. I will update the mod portal with the new location when the new version comes out.
