### ISSUE TITLE
Suggestion: Keybind to search all (not just inventory / logistic)

### ISSUE THREAD

**Issue by doktorstick** [raiguard/Factorio-SmallMods#9]
I frequently encounter a situation where I want to add a request to a temporary logistic slot only to be out of the item and out of logistic range. It would be nice if CTRL-F showed those items w/ a red background or have an alternative keybind that does CTRL-F plus the above. In this way, I can add it as a logistic request and the next time I'm in town, it'll be fulfilled. 

There are other times, albeit less often, I want to read an item's tooltip. Just using the alternative CTRL-F feature I mentioned before, saves me a keystroke or two since I don't have to open my inventory, first, before searching.

Your docs do indicate a "red" background, but I've yet to see it. The context makes me wonder if it's when you are in editor mode only.

**Comment by raiguard** [comment]
The mod should display unavailable items in red:

![image](https://user-images.githubusercontent.com/3515394/83084369-f9a8d380-a045-11ea-944c-07d7a5106f76.png)

Originally it was disabled by default, but now it's enabled by default. If you've been using the mod for more than a few days, you'll have to go enable it in the mod settings.

Unfortunately you can't set logistic requests on unavailable items, but that's definitely something I can see about adding, since I myself have wanted that ability a few times.

On another note, QIS now has its own repository [here](https://github.com/raiguard/Factorio-QuickItemSearch). So I'm going to close this issue. If you want to carry on the discussion, please open another issue over there. Thanks!
